server:
  port: 8080
storage:
  location: ./uploads

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://cruduser:xMGVtEJGuwNUgIUg@167.172.35.102:27017
      database: common
  elasticsearch:
    uris: ${ES_URI:localhost}:9200
  kafka:
    properties:
      bootstrap.servers: localhost:29092
      schema.registry.url: http://localhost:8081
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      listener:
        ack-mode: MANUAL_IMMEDIATE
      consumer:
        group-id: product-consumer-g1
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        properties:
          specific.avro.reader: true
topic:
  product: "product-topic"




